### PR TITLE
Refactor greGraphy data and nivo/chloropeth map.

### PR DESCRIPTION
**Pull request by Animesh239**
Add dropdown for sales per unit in form

### CODE REVIEW

**Comment by RickDeb2004** [comment]
can you share a ss?

**Comment by Animesh239** [comment]
image
The geography map is not responsive at the dashboard , so didn't add it

**Comment by RickDeb2004** [comment]
ok

**Comment by RickDeb2004** [comment]
connect with firebase db

**Comment by RickDeb2004** [comment]
share your mail and password which is needed to check the outcome

**Comment by Animesh239** [comment]
got it

**Pull request merged**
